version: '2'

services:
  web:
    image: nginx:latest
    container_name: web
    ports:
      - "80:8000"
    command: nginx-debug -g 'daemon off;'
    working_dir: /opt
    links:
      - php1
      - php2
      - php3
    networks:
      - develop
    volumes:
      - ./public:/opt/public
      - ./laravel.conf:/etc/nginx/conf.d/laravel.conf
    depends_on:
      - php1
      - php2
      - php3
  db:
    image: mysql
    container_name: database
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3306:3306"
    expose:
      - "3306"
    volumes:
      - $PWD/storage/database:/var/lib/mysql
    networks:
      - develop
    environment:
      MYSQL_ROOT_HOST: '%'
      MYSQL_DATABASE: 'laravel'
      MYSQL_USER: 'root'
      MYSQL_PASSWORD: 'secret'
      MYSQL_ROOT_PASSWORD: 'root'
  php1:
    image: php:7.3.4-fpm
    container_name: php1
    volumes:
      - .:/opt
    working_dir: /opt
    command: sh install.sh
    #user: dennys
    environment:
      INSTALL_VENDOR: 'y'
    networks:
      - develop
    depends_on:
      - db
    links:
      - db
  php2:
    image: php:7.3.4-fpm
    container_name: php2
    volumes:
      - .:/opt
    working_dir: /opt
    command: sh install.sh
    environment:
      INSTALL_VENDOR: 'n'
    networks:
      - develop
    depends_on:
      - db
    links:
      - db
  php3:
    image: php:7.3.4-fpm
    container_name: php3
    volumes:
      - .:/opt
    working_dir: /opt
    command: sh install.sh
    environment:
      INSTALL_VENDOR: 'n'
    networks:
      - develop
    depends_on:
      - db
    links:
      - db
networks:
  develop:
    driver: bridge
